/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PastWinnersRouteImport } from './routes/past-winners'
import { Route as GiveawaysIdRouteImport } from './routes/giveaways/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PastWinnersRoute = PastWinnersRouteImport.update({
  id: '/past-winners',
  path: '/past-winners',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveawaysIdRoute = GiveawaysIdRouteImport.update({
  id: '/giveaways/$id',
  path: '/giveaways/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/past-winners': typeof PastWinnersRoute
  '/giveaways/$id': typeof GiveawaysIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/past-winners': typeof PastWinnersRoute
  '/giveaways/$id': typeof GiveawaysIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/past-winners': typeof PastWinnersRoute
  '/giveaways/$id': typeof GiveawaysIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/past-winners' | '/giveaways/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/past-winners' | '/giveaways/$id'
  id: '__root__' | '/' | '/past-winners' | '/giveaways/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PastWinnersRoute: typeof PastWinnersRoute
  GiveawaysIdRoute: typeof GiveawaysIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-winners': {
      id: '/past-winners'
      path: '/past-winners'
      fullPath: '/past-winners'
      preLoaderRoute: typeof PastWinnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giveaways/$id': {
      id: '/giveaways/$id'
      path: '/giveaways/$id'
      fullPath: '/giveaways/$id'
      preLoaderRoute: typeof GiveawaysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PastWinnersRoute: PastWinnersRoute,
  GiveawaysIdRoute: GiveawaysIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
