/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PastWinnersRouteImport } from './routes/past-winners'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as GiveawaysIdRouteImport } from './routes/giveaways/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PastWinnersRoute = PastWinnersRouteImport.update({
  id: '/past-winners',
  path: '/past-winners',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveawaysIdRoute = GiveawaysIdRouteImport.update({
  id: '/giveaways/$id',
  path: '/giveaways/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/past-winners': typeof PastWinnersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/giveaways/$id': typeof GiveawaysIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/past-winners': typeof PastWinnersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/giveaways/$id': typeof GiveawaysIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/past-winners': typeof PastWinnersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/giveaways/$id': typeof GiveawaysIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin' | '/past-winners' | '/reset-password' | '/giveaways/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/past-winners' | '/reset-password' | '/giveaways/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/past-winners'
    | '/reset-password'
    | '/giveaways/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PastWinnersRoute: typeof PastWinnersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  GiveawaysIdRoute: typeof GiveawaysIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-winners': {
      id: '/past-winners'
      path: '/past-winners'
      fullPath: '/past-winners'
      preLoaderRoute: typeof PastWinnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giveaways/$id': {
      id: '/giveaways/$id'
      path: '/giveaways/$id'
      fullPath: '/giveaways/$id'
      preLoaderRoute: typeof GiveawaysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PastWinnersRoute: PastWinnersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  GiveawaysIdRoute: GiveawaysIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
